name: Google Cloud Run Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: latest

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build & Publish
      run: |
        docker build -t eu.gcr.io/${{ env.CLOUDSDK_CORE_PROJECT }}/${{ github.event.repository.name }} .
        docker push eu.gcr.io/${{ env.CLOUDSDK_CORE_PROJECT }}/${{ github.event.repository.name }}

    - name: Service Account Creation
      continue-on-error: true
      run: |
        gcloud iam service-accounts create ${{ github.event.repository.name }}@${{ env.CLOUDSDK_CORE_PROJECT }}.iam.gserviceaccount.com \
        --description="Service Account for Github repository: ${{ github.event.repository.name }}"

    - name: Deploy
      run: |
        gcloud run deploy ${{ github.event.repository.name }} --image eu.gcr.io/${{ env.CLOUDSDK_CORE_PROJECT }}/${{ github.event.repository.name }} \
        --project ${{ env.CLOUDSDK_CORE_PROJECT }} \
        --region europe-west1 \
        --platform managed \
        --no-allow-unauthenticated;