name: Google Cloud Run Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: latest

    - name: Get Project ID
      run: |
        PROJECT_ID=$(gcloud projects list --format 'value(PROJECT_NUMBER)')
        echo ${PROJECT_ID}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Service Account Creation
      continue-on-error: true
      run: |
        gcloud iam service-accounts create ${{ github.event.repository.name }} \
        --description="Service Account for Github repository: ${{ github.event.repository.name }}";

    - name: Role Assign
      run: |
        gcloud projects add-iam-policy-binding ${{ env.CLOUDSDK_CORE_PROJECT }} \
        --member=serviceAccount:${{ github.event.repository.name }}@${{ env.CLOUDSDK_CORE_PROJECT }}.iam.gserviceaccount.com \
        --role=roles/logging.logWrite

